services:
  # database
  mysql:
    container_name: dc-mysql
    image: bitnami/mysql
    volumes:
      - ./.docker/mysql:/docker-entrypoint-initdb.d
      - dc-mysql:/bitnami/mysql/data
    restart: always
    ports:
      - 3306:3306
    labels:
      - traefik.enable=false
    environment:
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=devchat
      - MYSQL_USER=devchat-dev
      - MYSQL_PASSWORD=password

volumes:
  dc-mysql: {}
